apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: spring
  labels:
    app: petclinic
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 25%
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: image-registry.openshift-image-registry.svc:5000/spring/petclinic:987eace5
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        # PostgreSQL environment variables
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://petclinic-db:5432/petclinic
        - name: SPRING_DATASOURCE_USERNAME
          value: petclinic
        - name: SPRING_DATASOURCE_PASSWORD
          value: petclinic
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta
