apiVersion: v1
kind: Service
metadata:
  name: petclinic-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: petclinic-db
    
---
kind: Service
apiVersion: v1
metadata:
  name: petclinic
  namespace: spring
spec:
  selector:
    app: petclinic
  ports:
  - protocol: TCP
    port: 8080
