apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    
---
kind: Service
apiVersion: v1
metadata:
  name: petclinic
  namespace: spring
spec:
  selector:
    app: petclinic
  ports:
  - protocol: TCP
    port: 8080
